//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sklep_Internetowy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        public int ID { get; set; }
        public string ProdType { get; set; }
        public string ProdName { get; set; }
        public string ProdDescription { get; set; }
        public Nullable<int> ProdPrice { get; set; }
    }
}
